name: Pipeline

on:
  push:
  workflow_dispatch:

jobs:

  Params:
    uses: pyTooling/Actions/.github/workflows/Parameters.yml@r0
    with:
      name: pyEDAA.UCIS

  BuildTheDocs:
    uses: pyTooling/Actions/.github/workflows/BuildTheDocs.yml@r0
    needs:
      - Params
    with:
      artifact: ${{ fromJson(needs.Params.outputs.params).artifacts.doc }}

  PublishToGitHubPages:
    uses: pyTooling/Actions/.github/workflows/PublishToGitHubPages.yml@r0
    needs:
      - Params
      - BuildTheDocs
    with:
      doc: ${{ fromJson(needs.Params.outputs.params).artifacts.doc }}

# TODO: this is disabled until some package exists.
#  ArtifactCleanUp:
#    uses: pyTooling/Actions/.github/workflows/ArtifactCleanUp.yml@r0
#    needs:
#      - Params
#      - BuildTheDocs
#      - PublishToGitHubPages
#    with:
#      package: ${{ fromJson(needs.Params.outputs.params).artifacts.package }}
#      remaining: |
#        ${{ fromJson(needs.Params.outputs.params).artifacts.doc }}
